### ISSUE TITLE
QAC reports with multiple dirty checksums produce invalid LOOT masterlist entries

### ISSUE THREAD

**Issue by sibir-ine** [TES5Edit/TES5Edit#1036]
**What is the version of xEdit you are using?**
FO3Edit 4.0.4c (Quick Auto Clean) (264F2054) starting session 2022-09-05 23:48:53
Applies to other xEdit game variations & v4.1.4c as well.

**Describe the bug**
QAC reports with multiple dirty checksums (e.g., plugins requiring multiple passes, plugins with deleted navmeshes) produce invalid LOOT masterlist entries as each dirty checksum has its own `dirty` YAML key.

**To reproduce**
1. Download & install a plugin, e.g., with deleted navmeshes (e.g., [this one](https://www.nexusmods.com/fallout3/mods/22168))
2. Clean the plugin with xEdit in QAC mode
3. Observe the generated LOOT masterlist entry with multiple `dirty` keys

**Expected behavior**
Duplicate YAML keys are not allowed, so there should only be one `dirty` key per plugin with each dirty checksum mapped to it.

**Additional context**
[Section](https://loot-api.readthedocs.io/en/stable/metadata/introduction.html) of LOOT's metadata syntax documentation summarizing the relevant YAML specs:
> That each key in a key-value map must only appear once per map object.

Example invalid LOOT masterlist entry generated by xEdit:
```yaml
  - name: 'FinalCourierMod.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x11516512
        util: '[FO3Edit v4.0.4c](https://www.nexusmods.com/fallout3/mods/637)'
        itm: 149
        udr: 9
        nav: 1
    dirty:
      - <<: *reqManualFix
        crc: 0x9870E320
        util: '[FO3Edit v4.0.4c](https://www.nexusmods.com/fallout3/mods/637)'
        nav: 1
```
